// قيم خيارات بعينها ترجمها صاحب هذه الشيفرة يدويًا (٢٤/٠٩/٢٦): آخر ٣١٦ سطرًا على الرف الحي يئس منها النموذج ثلاثًا
// ولا يجمعها نمط (أسماء رسومات، أكواد موردين، مقاسات بطول داخلي). المطابقة كاملة بلا حساسية لحالة الحروف.
// «القاموس يغلب النموذج» يطبّقها على الحي في الدفعة التالية. قيمة جديدة تتكرر ولا نمط لها ⟵ أضفها هنا.
export const MANUAL: Record<string, string> = {
  "black and white tail": "ذيل أسود وأبيض",
  "t003 # milky apricot color": "T003 مشمشي حليبي",
  "1608 # 1.0 gray (standard)": "1608 رمادي 1.0 (قياسي)",
  "sky blue long sleeve2": "سماوي بكم طويل 2",
  "short gray boots": "بوت قصير رمادي",
  "070 melody-white": "070 ميلودي أبيض",
  "single piece burgundy jacket": "جاكيت عنابي قطعة واحدة",
  "khaki basket with white edges": "سلة كاكي بحواف بيضاء",
  "navy blue (herringbone sling)": "كحلي بحزام متعرّج النقشة",
  "three cats gray": "رمادي بثلاث قطط",
  "short beige1": "بيج قصير 1",
  "6113-strawberry girl yellow": "6113 فتاة الفراولة أصفر",
  "6112-strawberry girl powder": "6112 فتاة الفراولة وردي",
  "4215-black snoopy": "4215 سنوبي أسود",
  "4208-balloon elephant": "4208 فيل البالون",
  "3485# (3485 hash)": "3485",
  "3175# stripes (cool ice silk)": "3175 مخطط (حرير بارد)",
  "294# plush kt": "294 كيتي بالفرو",
  "290#gold kt": "290 كيتي ذهبي",
  "289#starry sky gray kt": "289 كيتي رمادي سماء النجوم",
  "288#champagne gray kt": "288 كيتي رمادي شامبانيا",
  "18.1-3 yellow dots": "18.1-3 منقّط أصفر",
  "11.4 velvet 1314 rose red": "11.4 مخمل 1314 وردي غامق",
  "11.3 velvet 1314 powder": "11.3 مخمل 1314 وردي",
  "11.2 velvet 1314 gray": "11.2 مخمل 1314 رمادي",
  "1043-casual graffiti": "1043 رسومات غرافيتي",
  "khaki+peach blossoms": "كاكي بزهور الخوخ",
  "khaki [for petite individuals": "كاكي لقصيرات القامة",
  "khaki [regular": "كاكي عادي",
  "apricot color + peach blossoms": "مشمشي بزهور الخوخ",
  "52 # khaki crab headband": "52 طوق شعر كاكي بمشبك",
  "4 # black kitten (about 19cm)": "4 قطة سوداء (حوالي 19 سم)",
  "2406 croc shoes khaki [coal]": "2406 حذاء كروكس كاكي",
  "1818 coffee color [coal ball]": "1818 بني قهوة",
  "for 2-3 people": "لشخصين إلى 3 أشخاص",
  "l recommends around 57.5-65kg": "L (57.5-65 كغ)",
  "inner length 22.0cm in size 35": "مقاس 35 (طول داخلي 22.0 سم)",
  "consult customer service2": "اسألي خدمة الزبائن 2",
  "8w072 lingrui fairy fox set 6": "8W072 طقم الثعلب الجنّية 6",
  "17.0cm inside size 28": "مقاس 28 (طول داخلي 17.0 سم)",
  "-253 fortune fox fairy set 6": "253 طقم ثعلب الحظ 6",
  "【high quality】off-white": "أوف وايت (جودة عالية)",
  "【high quality】khaki color": "كاكي (جودة عالية)",
  "【beige】heavyweight 380 grams": "بيج ثقيل 380 غرام",
  "【145*13 angled ribbon】-1": "شريط مائل 145*13 - 1",
  "▼ off-white - washboard ▼": "أوف وايت مموّج",
  "▼ khaki-tofu block ▼": "كاكي بمربعات",
  "[dark green] thick style": "أخضر غامق سميك",
  "yellow [coffee lining]": "أصفر ببطانة بني قهوة",
  "ybl-a221 rose red (400 grams)": "YBL-A221 وردي غامق (400 غرام)",
  "ybl-a221 navy blue (400 grams)": "YBL-A221 كحلي (400 غرام)",
  "ybl-a219 rose red (310 grams)": "YBL-A219 وردي غامق (310 غرام)",
  "ybl-a219 dark gray (310 grams)": "YBL-A219 رمادي غامق (310 غرام)",
  "ybl-a219 navy blue (310 grams)": "YBL-A219 كحلي (310 غرام)",
  "ybl-a206 rose red (320 grams)": "YBL-A206 وردي غامق (320 غرام)",
  "ybl-a206 dark gray (320 grams)": "YBL-A206 رمادي غامق (320 غرام)",
  "ybl-a206 navy blue (320 grams)": "YBL-A206 كحلي (320 غرام)",
  "xizang gold": "ذهبي تبتي",
  "within s 47.5kg": "S (حتى 47.5 كغ)",
  "within m 50kg": "M (حتى 50 كغ)",
  "within l 70kg": "L (حتى 70 كغ)",
  "white doctor's coat and hat": "معطف طبيب أبيض مع قبعة",
  "white [coffee lining]": "أبيض ببطانة بني قهوة",
  "warm coffee": "بني قهوة دافئ",
  "violet [1 single seat]": "بنفسجي (مقعد فردي)",
  "velvet-red rainbow cat head": "مخمل أحمر برأس قطة قوس قزح",
  "thickened version [2 pieces]": "نسخة سميكة (قطعتان)",
  "thickened version [1 piece]": "نسخة سميكة (قطعة واحدة)",
  "striped pin buckle khaki": "كاكي مخطط بإبزيم دبوس",
  "sr-navy cashew": "SR كحلي بنقشة الكاجو",
  "sr-khaki perris": "SR كاكي بنقشة بيزلي",
  "small size square apricot": "مشمشي مربّع مقاس صغير",
  "small size rectangular apricot": "مشمشي مستطيل مقاس صغير",
  "small size m (height 150-160cm": "M صغير (الطول 150-160 سم)",
  "small size l (height 160-165cm": "L صغير (الطول 160-165 سم)",
  "small coffee": "بني قهوة صغير",
  "sjj162-beige 180*70cm)": "SJJ162 بيج 180*70 سم",
  "simple coffee": "بني قهوة سادة",
  "silver buckle s pebbled belt": "حزام محبّب بإبزيم فضي S",
  "sjk11 horsebit rose gold": "SJK11 حلقة الحصان ذهبي وردي",
  "s9061 # grayish green": "S9061 أخضر رمادي",
  "rz6575-navy edge": "RZ6575 بحافة كحلية",
  "rice apricot": "مشمشي فاتح",
  "regular model【1 piece】": "موديل عادي (قطعة واحدة)",
  "pink [coffee lining]": "وردي ببطانة بني قهوة",
  "phone stand - yellow - 1 piece": "حامل هاتف أصفر - قطعة واحدة",
  "phone stand - green - 1 piece": "حامل هاتف أخضر - قطعة واحدة",
  "phone stand - gray - 1 piece": "حامل هاتف رمادي - قطعة واحدة",
  "p629 rose gold silicone band": "P629 سوار سيليكون ذهبي وردي",
  "olive green - large size": "أخضر زيتي - مقاس كبير",
  "olive green - extra large size": "أخضر زيتي - مقاس كبير جدًا",
  "off-white - with pendant": "أوف وايت مع تعليقة",
  "navy blue pony + velvet cotton": "كحلي بنقشة المهر + قطن مخملي",
  "navy blue a219 (310g)": "كحلي A219 (310 غ)",
  "m【excellent quality】": "M (جودة ممتازة)",
  "m【high quality】": "M (جودة عالية)",
  "mkh-1703 emma orange (320g)": "MKH-1703 برتقالي (320 غ)",
  "m waist circumference 68": "M (محيط الخصر 68)",
  "m versatile": "M متعدد الاستعمال",
  "m recommended within 45-52.5kg": "M (45-52.5 كغ)",
  "l【excellent quality】": "L (جودة ممتازة)",
  "leopard head hollow gold alloy": "رأس نمر مفرّغ من سبيكة ذهبية",
  "lemon yellow extra large": "أصفر ليموني كبير جدًا",
  "laser s pebbled belt": "حزام محبّب ليزري بإبزيم S",
  "large rectangular apricot": "مشمشي مستطيل كبير",
  "lanyard style [1 pack]": "بحبل تعليق (عبوة واحدة)",
  "lake blue a219 (310g)": "أزرق بحري A219 (310 غ)",
  "l43-outer box 68*32*18cm+foam1": "L43 صندوق خارجي 68*32*18 سم + إسفنج 1",
  "l41-outer box 50*28*15cm+foam1": "L41 صندوق خارجي 50*28*15 سم + إسفنج 1",
  "l recommends 53kg-57.5kg": "L (53-57.5 كغ)",
  "l recommends 52.5kg-57.5kg": "L (52.5-57.5 كغ)",
  "l recommendations 55-62.5kg": "L (55-62.5 كغ)",
  "l recommendations 105-115": "L (105-115)",
  "l [2 feet 1]": "L (نوع 2-1)",
  "l recommended weight 40-50kg": "L (40-50 كغ)",
  "l (120-140) pounds": "L (120-140 رطل)",
  "khaki color comes with a bag": "كاكي مع حقيبة",
  "khaki color # 1840": "كاكي 1840",
  "khaki [2.8 side label letter]": "كاكي (ملصق جانبي 2.8)",
  "khaki crab headband": "طوق شعر كاكي بمشبك",
  "khaki + velvet cotton": "كاكي + قطن مخملي",
  "khaki + gray frog pendant": "كاكي + تعليقة ضفدع رمادية",
  "kameila k04 milk coffee": "K04 بني بالحليب",
  "inner length 25.0cm in size 39": "مقاس 39 (طول داخلي 25.0 سم)",
  "inner length 23.0cm in size 36": "مقاس 36 (طول داخلي 23.0 سم)",
  "imitation gold plated": "مطلي بلون ذهبي",
  "green [coffee lining]": "أخضر ببطانة بني قهوة",
  "gray-vertical lines※": "رمادي بخطوط طولية",
  "gray [1 single seat]": "رمادي (مقعد فردي)",
  "golden [coffee lining]": "ذهبي ببطانة بني قهوة",
  "gold tycoon gold": "ذهبي فاخر",
  "gold buckle s pebbled belt": "حزام محبّب بإبزيم ذهبي S",
  "gold [naked]]": "ذهبي بلا تغليف",
  "ginkgo leaf khaki": "كاكي بورق الجنكة",
  "fine gray stripes": "رمادي بخطوط رفيعة",
  "embroidered t-shirt navy blue": "تيشيرت مطرّز كحلي",
  "e02-hugging tiger": "E02 النمر المعانق",
  "dune gray powder palette #": "باليت بودرة رمادي رملي",
  "d48-8cm tie 10-scarlet vine": "D48 ربطة عنق 8 سم 10 قرمزي بنقشة الكرمة",
  "d48-8cm tie 09-new green vine": "D48 ربطة عنق 8 سم 09 أخضر بنقشة الكرمة",
  "d48-8cm tie 08-warm brown vine": "D48 ربطة عنق 8 سم 08 بني دافئ بنقشة الكرمة",
  "cxk006-yellow edge rose": "CXK006 وردة بحافة صفراء",
  "cxk005-navy red cashew nuts": "CXK005 كحلي وأحمر بنقشة الكاجو",
  "cxk005-coffee color polka dots": "CXK005 بني قهوة منقّط",
  "cxk005 - burgundy cashew": "CXK005 عنابي بنقشة الكاجو",
  "crown skirt navy blue": "تنورة كحلي بنقشة التاج",
  "cream white [1 pack]": "أبيض كريمي (عبوة واحدة)",
  "covers-navy blue": "أغطية كحلي",
  "consult customer service1": "اسألي خدمة الزبائن 1",
  "color blue gold label": "أزرق بملصق ذهبي",
  "coffee flower + velvet cotton": "بني قهوة بالورود + قطن مخملي",
  "coffee gold label": "بني قهوة بملصق ذهبي",
  "clover red coffee": "بني قهوة وأحمر بنقشة البرسيم",
  "carmela 07 maple red brown": "07 بني محمرّ",
  "burgundy [rear seat bench]": "عنابي (مقعد خلفي)",
  "brown - without accessories1": "بني بلا إكسسوارات 1",
  "blue-striped puppy": "أزرق مخطط بجرو",
  "blue [coffee lining]": "أزرق ببطانة بني قهوة",
  "black [1 pack]": "أسود (عبوة واحدة)",
  "beige [1 single seat]": "بيج (مقعد فردي)",
  "beige [1 backrest]": "بيج (مسند ظهر واحد)",
  "beige sw-270 [diameter 30cm": "بيج SW-270 (قطر 30 سم)",
  "beige sw-260 [diameter 27cm": "بيج SW-260 (قطر 27 سم)",
  "beige sw-240 [diameter 23.5cm": "بيج SW-240 (قطر 23.5 سم)",
  "beige sw-180 [diameter 18cm": "بيج SW-180 (قطر 18 سم)",
  "apricot my+ velvet cotton": "مشمشي + قطن مخملي",
  "apricot a219 (310g)": "مشمشي A219 (310 غ)",
  "almond beige": "بيج لوزي",
  "added #brown": "بني (إضافي)",
  "added #apricot": "مشمشي (إضافي)",
  "54 # orange peel oolong": "54 شاي أولونغ بقشر البرتقال",
  "5039 black gray flower": "5039 ورد أسود ورمادي",
  "40-year-old woman": "لسيدة في عمر 40",
  "4 # navy blue denim": "4 دنيم كحلي",
  "30ml ice cream (white 838)": "30 مل آيس كريم (أبيض 838)",
  "3 # purple coffee color": "3 بني قهوة بنفسجي",
  "2nd floor": "طبقتان",
  "220v] + 1 spare filter element": "220 فولت + فلتر احتياطي",
  "1【standard version】protractor": "1 منقلة (نسخة قياسية)",
  "1# off-white about 1.2cm": "1 أوف وايت حوالي 1.2 سم",
  "01#ivory white": "01 عاجي",
  "003# sapphire blue": "003 أزرق ياقوتي",
  ".khaki [small saddle bag]": "كاكي (حقيبة سرج صغيرة)",
  ".khaki [large saddle bag]": "كاكي (حقيبة سرج كبيرة)",
  "# 01 porcelain white": "01 أبيض خزفي",
  "\"fireworks\" black gold edition": "إصدار الألعاب النارية أسود وذهبي",
};
